CREATE TABLE balance_sheet_qtr (
	id BIGSERIAL NOT NULL PRIMARY KEY,
    instrument_id BIGINT NOT NULL,    
    interval_end_date DATE NOT NULL, 
    filing_date DATE, 
    currency_symbol VARCHAR(10), 
    total_assets NUMERIC,
    intangible_assets NUMERIC, 
    earning_assets NUMERIC, 
    other_current_assets NUMERIC,
    total_liab NUMERIC, 
    total_stockholder_equity NUMERIC, 
    deferred_long_term_liab NUMERIC,
    other_current_liab NUMERIC, 
    common_stock NUMERIC, 
    capital_stock NUMERIC,
    retained_earnings NUMERIC, 
    other_liab NUMERIC, 
    good_will NUMERIC, 
    other_assets NUMERIC, 
    cash NUMERIC,
    cash_and_equivalents NUMERIC, 
    total_current_liabilities NUMERIC,
    current_deferred_revenue NUMERIC, 
    net_debt NUMERIC, 
    short_term_debt NUMERIC,
    short_long_term_debt NUMERIC,
    short_long_term_debt_total NUMERIC,
    other_stockholder_equity NUMERIC, 
    property_plant_equipment NUMERIC,
    total_current_assets NUMERIC, 
    long_term_investments NUMERIC, 
    net_tangible_assets NUMERIC,
    short_term_investments NUMERIC, 
    net_receivables NUMERIC, 
    long_term_debt NUMERIC,
    inventory NUMERIC, 
    accounts_payable NUMERIC, 
    total_permanent_equity NUMERIC,
    noncontrolling_interest_in_consolidated_entity NUMERIC,
    temporary_equity_redeemable_noncontrolling_interests NUMERIC,
    accumulated_other_comprehensive_income NUMERIC, 
    additional_paid_in_capital NUMERIC,
    common_stock_total_equity NUMERIC, 
    preferred_stock_total_equity NUMERIC,
    retained_earnings_total_equity NUMERIC, 
    treasury_stock NUMERIC,
    accumulated_amortization NUMERIC, 
    non_currrent_assets_other NUMERIC,
    deferred_long_term_asset_charges NUMERIC, 
    non_current_assets_total NUMERIC,
    capital_lease_obligations NUMERIC, 
    long_term_debt_total NUMERIC,
    non_current_liabilities_other NUMERIC, 
    non_current_liabilities_total NUMERIC,
    negative_goodwill NUMERIC, 
    warrants NUMERIC, 
    preferred_stock_redeemable NUMERIC,
    capital_surpluse NUMERIC, 
    liabilities_and_stockholders_equity NUMERIC,
    cash_and_short_term_investments NUMERIC, 
    property_plant_and_equipment_gross NUMERIC,
    property_plant_and_equipment_net NUMERIC, 
    accumulated_depreciation NUMERIC,
    net_working_capital NUMERIC, 
    net_invested_capital NUMERIC,
    common_stock_shares_outstanding NUMERIC,
    created_date DATE NOT NULL, 
	last_update_date DATE NOT NULL
);