CREATE TABLE cash_flow_yr (
	id BIGSERIAL NOT NULL PRIMARY KEY,
    instrument_id BIGINT NOT NULL,    
    interval_end_date DATE NOT NULL, 
    filing_date DATE, 
    currency_symbol VARCHAR(10),
    investments NUMERIC,
    change_to_liabilities NUMERIC,
    total_cashflows_from_investing_activities NUMERIC,
    net_borrowings NUMERIC,
    total_cash_from_financing_activities NUMERIC,
    change_to_operating_activities NUMERIC,
    net_income NUMERIC,
    change_in_cash NUMERIC,
    begin_period_cash_flow NUMERIC,
    end_period_cash_flow NUMERIC,
    total_cash_from_operating_activities NUMERIC,
    issuance_of_capital_stock NUMERIC,
    depreciation NUMERIC,
    other_cashflows_from_investing_activities NUMERIC,
    dividends_paid NUMERIC,
    change_to_inventory NUMERIC,
    change_to_account_receivables NUMERIC,
    sale_purchase_of_stock NUMERIC,
    other_cashflows_from_financing_activities NUMERIC,
    change_to_netincome NUMERIC,
    capital_expenditures NUMERIC,
    change_receivables NUMERIC,
    cash_flows_other_operating NUMERIC,
    exchange_rate_changes NUMERIC,
    cash_and_cash_equivalents_changes NUMERIC,
    change_in_working_capital NUMERIC,
    stock_based_compensation NUMERIC,
    other_non_cash_items NUMERIC,
    free_cash_flow NUMERIC,
    created_date DATE NOT NULL, 
	last_update_date DATE NOT NULL
);
