CREATE TABLE company_fundamentals (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	instrument_id BIGINT NOT NULL,
    market_cap NUMERIC, 
    ebitda NUMERIC, 
    pe_ratio NUMERIC,  
    peg_ratio NUMERIC ,
    target_price NUMERIC, 
    book_value NUMERIC, 
    dps NUMERIC, 
    div_yield NUMERIC, 
    eps NUMERIC, 
    eps_est_fy0 NUMERIC, 
    eps_est_fy1 NUMERIC, 
    eps_est_q0 NUMERIC, 
    eps_est_q1 NUMERIC, 
    mrq varchar(50), 
    prof_margin NUMERIC, 
    op_margin NUMERIC, 
    roa NUMERIC, 
    roe NUMERIC, 
    sales NUMERIC, 
    sps NUMERIC, 
    qtrly_sales_growth_yoy NUMERIC, 
    qtrly_earnings_growth_yoy NUMERIC, 
    gross_profit NUMERIC, 
    dil_eps NUMERIC, 
    trailing_pe_ratio NUMERIC, 
    forward_pe_ratio NUMERIC, 
    ps_ratio NUMERIC, 
    pb_ratio NUMERIC, 
    ev_sales NUMERIC, 
    ev_ebitba NUMERIC,
	created_date DATE NOT NULL, 
	last_update_date DATE NOT NULL
);