CREATE TABLE earnings_trend (
	id BIGSERIAL NOT NULL PRIMARY KEY,
    instrument_id BIGINT NOT NULL,
	interval_end_date DATE NOT NULL,
    period VARCHAR(50),
    growth NUMERIC, 
    earnings_estimate_avg NUMERIC,
    earnings_estimate_low NUMERIC, 
    earnings_estimate_high NUMERIC,
    earnings_estimate_year_ago_eps NUMERIC,
    earnings_estimate_number_of_analysts NUMERIC,
    earnings_estimate_growth NUMERIC,
    revenue_estimate_avg NUMERIC, 
    revenue_estimate_low NUMERIC, 
    revenue_estimate_high NUMERIC,
    revenue_estimate_year_ago_eps NUMERIC, 
    revenue_estimate_number_of_analysts NUMERIC,
    revenue_estimate_growth NUMERIC, 
    eps_trend_current NUMERIC, 
    eps_trend7days_ago NUMERIC,
    eps_trend30days_ago NUMERIC, 
    eps_trend60days_ago NUMERIC, 
    eps_trend90days_ago NUMERIC,
    eps_revisions_up_last7days NUMERIC, 
    eps_revisions_up_last30days NUMERIC,
    eps_revisions_down_last7days NUMERIC, 
    eps_revisions_down_last30days NUMERIC, 
	created_date DATE NOT NULL, 
	last_update_date DATE NOT NULL
);