CREATE TABLE fundamentals_snapshot (
	id BIGSERIAL NOT NULL PRIMARY KEY,
    instrument_id BIGINT NOT NULL,    
    latest_date DATE NOT NULL, 
    ticker VARCHAR(10),
    instrument_type VARCHAR(50),
    name VARCHAR(100),
    exchange VARCHAR(10),
    currency_code VARCHAR(10),
    currency_name VARCHAR(50),
    currency_symbol VARCHAR(10),
    country_name VARCHAR(50),
    country_iso VARCHAR(10),
    open_figi VARCHAR(50),
    isin VARCHAR(20),
    lei VARCHAR(20),
    primary_ticker VARCHAR(10),
    cusip VARCHAR(20),
    cik VARCHAR(20),
    employer_id_number VARCHAR(50),
    fiscal_year_end VARCHAR(10),
    ipo_date DATE,
    international_domestic VARCHAR(20),
    sector VARCHAR(50),
    industry VARCHAR(50),
    gic_sector VARCHAR(50),
    gic_group VARCHAR(50),
    gic_industry VARCHAR(50),
    gic_sub_industry VARCHAR(50),
    home_category VARCHAR(50),
    is_delisted BOOLEAN,
    -- description VARCHAR(50),
    -- address NUMERIC,
    -- phone NUMERIC,
    web_url VARCHAR(50),
    logo_url VARCHAR(50),
    full_time_employees NUMERIC,
    updated_at DATE,
    market_capitalization NUMERIC,
    market_capitalization_mln NUMERIC,
    ebitda NUMERIC,
    pe_ratio NUMERIC,
    peg_ratio NUMERIC,
    wall_street_target_price NUMERIC,
    book_value NUMERIC,
    dividend_share NUMERIC,
    dividend_yield NUMERIC,
    earnings_share NUMERIC,
    eps_estimate_current_year NUMERIC,
    eps_estimate_next_year NUMERIC,
    eps_estimate_next_quarter NUMERIC,
    eps_estimate_current_quarter NUMERIC,
    most_recent_quarter DATE,
    profit_margin NUMERIC,
    operating_margin_ttm NUMERIC,
    return_on_assets_ttm NUMERIC,
    return_on_equity_ttm NUMERIC,
    revenue_ttm NUMERIC,
    revenue_per_share_ttm NUMERIC,
    quarterly_revenue_growth_yoy NUMERIC,
    gross_profit_ttm NUMERIC,
    diluted_eps_ttm NUMERIC,
    quarterly_earnings_growth_yoy NUMERIC,
    trailing_pe NUMERIC,
    forward_pe NUMERIC,
    price_sales_ttm NUMERIC,
    price_book_mrq NUMERIC,
    enterprise_value NUMERIC,
    enterprise_value_revenue NUMERIC,
    enterprise_value_ebitda NUMERIC,
    shares_outstanding NUMERIC,
    shares_float NUMERIC,
    percent_insiders NUMERIC,
    percent_institutions NUMERIC,
    shares_short NUMERIC,
    shares_short_prior_month NUMERIC,
    short_ratio VARCHAR(10),
    short_percent_outstanding NUMERIC,
    short_percent_float NUMERIC,
    forward_annual_dividend_rate NUMERIC,
    forward_annual_dividend_yield NUMERIC,
    payout_ratio VARCHAR(10),
    dividend_date DATE,
    ex_dividend_date DATE,
    last_split_factor NUMERIC,
    last_split_date DATE,
    rating NUMERIC,
    target_price NUMERIC,
    strong_buy NUMERIC,
    buy NUMERIC,
    hold NUMERIC,
    sell NUMERIC,
    strong_sell NUMERIC,
    created_date DATE NOT NULL, 
	last_update_date DATE NOT NULL
);
