CREATE TABLE income_statement_qtr (
	id BIGSERIAL NOT NULL PRIMARY KEY,
    instrument_id BIGINT NOT NULL,    
    interval_end_date DATE NOT NULL, 
    filing_date DATE, 
    currency_symbol VARCHAR(10),
    research_development NUMERIC,
    effect_of_accounting_charges NUMERIC,
    income_before_tax NUMERIC,
    minority_interest NUMERIC,
    net_income NUMERIC,
    selling_general_administrative NUMERIC,
    selling_and_marketing_expenses NUMERIC,
    gross_profit NUMERIC,
    reconciled_depreciation NUMERIC,
    ebit NUMERIC,
    ebitda NUMERIC,
    depreciation_and_amortization NUMERIC,
    non_operating_income_net_other NUMERIC,
    operating_income NUMERIC,
    other_operating_expenses NUMERIC,
    interest_expense NUMERIC,
    tax_provision NUMERIC,
    interest_income NUMERIC,
    net_interest_income NUMERIC,
    extraordinary_items NUMERIC,
    non_recurring NUMERIC,
    other_items NUMERIC,
    income_tax_expense NUMERIC,
    total_revenue NUMERIC,
    total_operating_expenses NUMERIC,
    cost_of_revenue NUMERIC,
    total_other_income_expense_net NUMERIC,
    discontinued_operations NUMERIC,
    net_income_from_continuing_ops NUMERIC,
    net_income_applicable_to_common_shares NUMERIC,
    preferred_stock_and_other_adjustments NUMERIC,
    created_date DATE NOT NULL, 
	last_update_date DATE NOT NULL
);

